/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import napakalaki.BadConsequence;

/**
 *
 * @author juane
 */
public class BadConsequenceView extends javax.swing.JPanel {
    BadConsequence bad_model;
    /**
     * Creates new form BadConsequenceView
     */
    public BadConsequenceView() {
        initComponents();
    }

    public void setBad(BadConsequence p_bad){
        bad_model= p_bad;
        
        this.ind_descr_bad.setText(bad_model.getText());
        
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_tittle_bad = new javax.swing.JLabel();
        ind_descr_bad = new javax.swing.JLabel();

        setBorder(null);

        l_tittle_bad.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        l_tittle_bad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_tittle_bad.setText("BAD CONSEQUENCE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ind_descr_bad, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_tittle_bad, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_tittle_bad)
                .addGap(18, 18, 18)
                .addComponent(ind_descr_bad, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ind_descr_bad;
    private javax.swing.JLabel l_tittle_bad;
    // End of variables declaration//GEN-END:variables
}
