/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JPanel;
import napakalaki.Napakalaki;
import napakalaki.Player;
import napakalaki.Treasure;

/**
 *
 * @author adr_i
 */
public class PlayerView extends javax.swing.JPanel {
    
    Player playerModel = null;
    private Napakalaki napakalakiModel = null;

    /**
     * Creates new form PlayerView
     */
    public PlayerView() {
        initComponents();
    }
    
    public void setNapakalaki(Napakalaki n){
        napakalakiModel = n;
    }
    
    private ArrayList<Treasure> getSelectedTreasures(JPanel aPanel) {
        // Se recorren los tesoros que contiene el panel,
        // almacenando en un vector aquellos que están seleccionados.
        // Finalmente se devuelve dicho vector.
        TreasureView tv;
        ArrayList<Treasure> output = new ArrayList();
        for (Component c : aPanel.getComponents()) {
            tv = (TreasureView) c;
            if ( tv.isSelected() )
             output.add ( tv.getTreasure() );
        }
        return output;
    }
    
    public void setPlayer (Player p) {
        playerModel = p;
        // Incluir instrucciones para actualizar su nombre, nivel, etc.
        this.ind_name_player.setText(playerModel.getName());
        this.ind_level_player.setText(Integer.toString(playerModel.getLevels()));
        this.ind_combatlevel_player.setText(Integer.toString(playerModel.getCombatLevel()));
        //MUERTE: this.ind_dead.setText(playerModel.get());
        
        // A continuación se actualizan sus tesoros
        fillTreasurePanel (p_visT_player, playerModel.getVisibleTreasures());
        fillTreasurePanel (p_hidT_player, playerModel.getHiddenTreasures());
        //this.pendingBadConsequenceView1.setPendingBad(playerModel.getPendingBadConsequence());
        repaint();
        revalidate();
    }
    
    private void fillTreasurePanel (JPanel aPanel, ArrayList<Treasure> aList) {
        // Se elimina la información antigua
        aPanel.removeAll();
        // Se recorre la lista de tesoros construyendo y añadiendo sus vistas
        //al panel
        for (Treasure t : aList) {
            TreasureView aTreasureView= new TreasureView();
            aTreasureView.setTreasure(t);
            aTreasureView.setVisible (true);
            aPanel.add (aTreasureView);
            aPanel.setVisible(true);
        }
        // Se fuerza la actualización visual del panel
        aPanel.repaint();
        aPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ind_name_player = new javax.swing.JLabel();
        pan_levels_player = new javax.swing.JPanel();
        pan_level_player = new javax.swing.JPanel();
        l_level_player = new javax.swing.JLabel();
        ind_level_player = new javax.swing.JLabel();
        pan_combatlevel_player = new javax.swing.JPanel();
        l_combat_player = new javax.swing.JLabel();
        ind_combatlevel_player = new javax.swing.JLabel();
        pan_botones_player = new javax.swing.JPanel();
        makevisible = new javax.swing.JButton();
        stealbutton = new javax.swing.JButton();
        discard_button = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        p_visT_player = new javax.swing.JPanel();
        p_hidT_player = new javax.swing.JPanel();

        ind_name_player.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        ind_name_player.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ind_name_player.setText("Nombre: ");

        l_level_player.setText("Player Level");

        ind_level_player.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        ind_level_player.setText("jLabel3");

        javax.swing.GroupLayout pan_level_playerLayout = new javax.swing.GroupLayout(pan_level_player);
        pan_level_player.setLayout(pan_level_playerLayout);
        pan_level_playerLayout.setHorizontalGroup(
            pan_level_playerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_level_playerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pan_level_playerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ind_level_player)
                    .addComponent(l_level_player))
                .addGap(53, 53, 53))
        );
        pan_level_playerLayout.setVerticalGroup(
            pan_level_playerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_level_playerLayout.createSequentialGroup()
                .addComponent(l_level_player)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(ind_level_player)
                .addGap(28, 28, 28))
        );

        l_combat_player.setText("CombatLevel");

        ind_combatlevel_player.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        ind_combatlevel_player.setText("jLabel3");

        javax.swing.GroupLayout pan_combatlevel_playerLayout = new javax.swing.GroupLayout(pan_combatlevel_player);
        pan_combatlevel_player.setLayout(pan_combatlevel_playerLayout);
        pan_combatlevel_playerLayout.setHorizontalGroup(
            pan_combatlevel_playerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_combatlevel_playerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pan_combatlevel_playerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_combat_player)
                    .addGroup(pan_combatlevel_playerLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(ind_combatlevel_player)))
                .addGap(53, 53, 53))
        );
        pan_combatlevel_playerLayout.setVerticalGroup(
            pan_combatlevel_playerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_combatlevel_playerLayout.createSequentialGroup()
                .addComponent(l_combat_player)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ind_combatlevel_player)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout pan_levels_playerLayout = new javax.swing.GroupLayout(pan_levels_player);
        pan_levels_player.setLayout(pan_levels_playerLayout);
        pan_levels_playerLayout.setHorizontalGroup(
            pan_levels_playerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_levels_playerLayout.createSequentialGroup()
                .addComponent(pan_level_player, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pan_combatlevel_player, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pan_levels_playerLayout.setVerticalGroup(
            pan_levels_playerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan_level_player, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pan_combatlevel_player, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        makevisible.setText("Make Visible");
        makevisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makevisibleActionPerformed(evt);
            }
        });

        stealbutton.setText("Steal Treasure");
        stealbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stealbuttonActionPerformed(evt);
            }
        });

        discard_button.setText("Discard Treasure");
        discard_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discard_buttonActionPerformed(evt);
            }
        });

        jButton1.setText("Discard All Treasures");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_botones_playerLayout = new javax.swing.GroupLayout(pan_botones_player);
        pan_botones_player.setLayout(pan_botones_playerLayout);
        pan_botones_playerLayout.setHorizontalGroup(
            pan_botones_playerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_botones_playerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_botones_playerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(makevisible)
                    .addComponent(discard_button)
                    .addComponent(stealbutton)
                    .addComponent(jButton1))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        pan_botones_playerLayout.setVerticalGroup(
            pan_botones_playerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_botones_playerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(makevisible)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(discard_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stealbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p_visT_player.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Visible Treasures", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        p_visT_player.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        p_hidT_player.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hidden Treasures", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        p_hidT_player.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pan_levels_player, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(ind_name_player, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pan_botones_player, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p_visT_player, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_hidT_player, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(ind_name_player, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pan_levels_player, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(p_visT_player, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pan_botones_player, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_hidT_player, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void makevisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makevisibleActionPerformed
        ArrayList<Treasure> selHidden = getSelectedTreasures(p_hidT_player);
        napakalakiModel.makeTreasuresVisible(selHidden);
        setPlayer (napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_makevisibleActionPerformed

    private void stealbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stealbuttonActionPerformed
        if(playerModel.canISteal())
            playerModel.stealTreasure();
    }//GEN-LAST:event_stealbuttonActionPerformed

    private void discard_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discard_buttonActionPerformed
        ArrayList<Treasure> selHidden = getSelectedTreasures(p_hidT_player);
        ArrayList<Treasure> selVisible = getSelectedTreasures(p_visT_player);
        napakalakiModel.discardHiddenTreasures(selHidden);
        napakalakiModel.discardVisibleTreasures(selVisible);
        setPlayer (napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_discard_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        playerModel.discardAllTreasures();
        setPlayer (napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton discard_button;
    private javax.swing.JLabel ind_combatlevel_player;
    private javax.swing.JLabel ind_level_player;
    private javax.swing.JLabel ind_name_player;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel l_combat_player;
    private javax.swing.JLabel l_level_player;
    private javax.swing.JButton makevisible;
    private javax.swing.JPanel p_hidT_player;
    private javax.swing.JPanel p_visT_player;
    private javax.swing.JPanel pan_botones_player;
    private javax.swing.JPanel pan_combatlevel_player;
    private javax.swing.JPanel pan_level_player;
    private javax.swing.JPanel pan_levels_player;
    private javax.swing.JButton stealbutton;
    // End of variables declaration//GEN-END:variables
}
